package com.example.facerecognizationattendancemanagement

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * FaceViewModel acts as a bridge between the UI (MainActivity) and the data layer (FaceRepository).
 * It uses Coroutines to ensure that database operations do not block the main thread.
 */
class FaceViewModel(application: Application) : AndroidViewModel(application) {

    // Internal reference to the repository
    private val repository = FaceRepository(application)

    /**
     * Persists a new user's face data to the local database.
     * @param userId Unique identifier for the person.
     * @param name Person's full name.
     * @param embedding The 192-float vector generated by MobileFaceNet.
     */
    fun saveUser(userId: String, name: String, embedding: FloatArray) {
        // Run on IO dispatcher to avoid UI jank
        viewModelScope.launch(Dispatchers.IO) {
            repository.saveUser(userId, name, embedding)
        }
    }

    /**
     * Retrieves all enrolled users from the database.
     * This is a suspend function meant to be called from a coroutine scope.
     */
    suspend fun getAllUsers(): List<UserEntity> {
        return withContext(Dispatchers.IO) {
            repository.getAllUsers()
        }
    }
}
