package com.example.facerecognizationattendancemanagement

import android.content.Context

/**
 * FaceRepository abstracts access to the user database.
 * It provides a clean API for the rest of the app to perform CRUD operations
 * on face enrollment data.
 */
class FaceRepository(context: Context) {

    // Get an instance of the DAO via the Database Singleton
    private val userDao = UserDatabase
        .getInstance(context)
        .userDao()

    /**
     * Creates or updates a user entry in the local Room database.
     * @param id Unique ID for the user.
     * @param name User's display name.
     * @param embedding The biometric vector generated by the ML model.
     */
    fun saveUser(
        id: String,
        name: String,
        embedding: FloatArray
    ) {
        userDao.insertUser(
            UserEntity(id, name, embedding)
        )
    }

    /**
     * Fetches all enrolled users.
     * Typically called when initializing the face recognition engine to load
     * known faces into memory.
     */
    fun getAllUsers(): List<UserEntity> {
        return userDao.getAllUsers()
    }
}
